name: build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Create build directory
      run: mkdir -p auto_system_api/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/auto_system_api/build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/auto_system_api/build
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/auto_system_api/build
      run: ctest -C ${{env.BUILD_TYPE}}
