name: build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  HOME: /root

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/takanotaiga/buck2_docker:latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup gtest
      uses: actions/checkout@v4
      with:
        repository: takanotaiga/gtest
        path: third_party/gtest
        fetch-depth: 0

    - name: Build
      run: buck2 build //...

    - name: Auto System API Test
      run: buck2 test //auto_system_api/test:test_ipc_backend
